AWSTemplateFormatVersion: 2010-09-09
Description: AWS Study
Metadata: 

Parameters: 

Mappings: 

Conditions: 

Resources: 
################################
# VPC
################################
  cfnVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: cfn-vpc
################################
# Subnet
################################
  cfnPublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref cfnVPC
      CidrBlock: 10.0.11.0/24
      Tags:
        - Key: Name
          Value: cfn-vpc-public-1a
  cfnPublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref cfnVPC
      CidrBlock: 10.0.12.0/24
      Tags:
        - Key: Name
          Value: cfn-vpc-public-1c
################################
# Gateway
################################
  cfnInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: cfn-vpc-igw
  cfnAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref cfnVPC
      InternetGatewayId: !Ref cfnInternetGateway
################################
# PublicRoute
################################
  cfnRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref cfnVPC
      Tags:
        - Key: Name
          Value: cfn-vpc-public-rt
  routeName:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref cfnRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref cfnInternetGateway
  cfnRouteTableAssocName:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref cfnPublicSubnet1a
      RouteTableId: !Ref cfnRouteTable
Outputs: